# Generated by Django 4.2 on 2025-12-16 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'admin'), ('Author', 'author'), ('Viewer', 'viewer')], default='Author', max_length=10),
        ),
    ]
