# Generated by Django 4.2 on 2025-12-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'approved'), ('REJECTED', 'rejected')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('AUTHOR', 'author'), ('Viewer', 'viewer')], default='AUTHOR', max_length=10),
        ),
    ]
