# Generated by Django 4.2 on 2025-12-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_post_status_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('AUTHOR', 'Author'), ('Viewer', 'Viewer')], default='AUTHOR', max_length=10),
        ),
    ]
